networks:
  vsl-network:
    name: vsl-network
    driver: bridge

services:
  vsl-core:
    image: ghcr.io/pi-squared-inc/vsl/vsl-core:vsl-devnet
    ports:
      - "44444:44444"
    networks:
      - vsl-network
    command: ["--use-genesis"]
    healthcheck:
      test:
        - "CMD"
        - "curl"
        - "-X"
        - "POST"
        - "-H"
        - "Content-Type: application/json"
        - "-d"
        - '{"jsonrpc":"2.0","id":"id","method":"vsl_getHealth"}'
        - "http://localhost:44444"
      interval: 1s
      timeout: 5s
      retries: 30
    volumes:
      - ./genesis.json:/genesis.json:ro
