services:
  claim-verifier:
    network_mode: host
    build:
      context: ./claim-verifier
      dockerfile: Dockerfile
      additional_contexts:
        root: ../../../
    env_file:
      - ./claim-verifier/.env

  claim-submitter:
    network_mode: host
    build:
      context: ./claim-submitter
      dockerfile: Dockerfile
      additional_contexts:
        root: ../../../
    env_file:
      - ./claim-submitter/.env
    depends_on:
      - claim-verifier
