[profile.default]
fs_permissions = [
    { access = "read", path = "./" },
    { access = "write", path = "./cache" },
]
libs = ["lib"]
out = "out"
src = "src"
remappings = [
    "ntt=lib/example-native-token-transfers/evm/src",
    "openzeppelin-contracts-5-0-1=lib/openzeppelin-contracts-5-0-1",
    "openzeppelin-contracts/=lib/example-native-token-transfers/evm/lib/openzeppelin-contracts",
]
optimizer = true
optimizer_runs = 200
evm_version = "london"
via_ir = true